### PR TITLE
Searchbar added.

### PR DESCRIPTION
**Pull request by ugurcankuzu**
- Searchbar added to Nav component.
- SearchResults component lists query results.
- Not focused on styling. It can be changed if needed.

### CODE REVIEW

**Comment by nitin-pandita** [comment]
Please share a screenShot

**Review by nitin-pandita — CHANGES_REQUESTED** [review]
Please attach a screenshot or a small video of the changes

**Comment by ugurcankuzu** [comment]
Sorry for late answer. Here you can see screenshots that belongs to changes.
Ekran Resmi 2023-07-22 13 39 40
Ekran Resmi 2023-07-22 13 39 26

**Comment by nitin-pandita** [comment]
> Sorry for late answer. Here you can see screenshots that belongs to changes. Ekran Resmi 2023-07-22 13 39 40 Ekran Resmi 2023-07-22 13 39 26

It looks great, good job

**Pull request merged**
